server:
  port: 8080
spring:
  application:
    name: "CrediYaAuthentication"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
    r2dbc:
      host: "localhost"
      port: 5432
      database: "mi_base"
      schema: "public"
      username: "admin"
      password: "admin123"
logging:
  level:
    root: INFO
    co.com.crediyaauthentication: TRACE
#    org.springframework.r2dbc: DEBUG
    org.springframework.security.web: DEBUG
    web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"

jwt:
  secret-key: 710a189e7de25e8e8035dcf7dc54e086a169700068965fd03f4b0a1b8b048f5d
  expiration-time: 300000